import { and, eq, gt, isNull } from 'drizzle-orm'
import type { Database } from '@infra/db/client'
import { componentSessions } from '@infra/db/schema'

export type ComponentSessionRow = typeof componentSessions.$inferSelect
export type ComponentSessionMode = ComponentSessionRow['mode']

export interface ComponentSessionInsert {
  projectId: string
  mode: ComponentSessionMode
  /** Stamped onto the domain claim this session eventually spends into — see `infra/db/schema.ts`'s `component_sessions.external_id` doc comment. */
  externalId?: string
  /** The session's own bearer credential — see `infra/db/schema.ts`'s doc comment. Generated by the caller via core's `generateToken()`. */
  token: string
  expiresAt: Date
}

/**
 * All db access for the component-sessions module — the `component_sessions`
 * table, a single bounded concept (a mint-once, spend-once claim
 * authorization). This is the only file in `modules/component-sessions`
 * allowed to import `@infra/db`.
 */
export interface ComponentSessionsRepository {
  /** Inserts a freshly minted session. */
  create(values: ComponentSessionInsert): Promise<ComponentSessionRow>

  /**
   * Atomically spends a session: flips `consumed_at` from `null` to `now`
   * in one `UPDATE ... WHERE consumed_at IS NULL AND expires_at > now
   * RETURNING`, only if the session is still unconsumed and unexpired.
   * The row lock this update acquires is what makes "exactly one claim per
   * session" hold even under two concurrent requests racing on the same
   * token — not just sequential double-claim attempts. Returns
   * `undefined` for an unknown, already-consumed, or expired token,
   * indistinguishable from each other — same anti-enumeration stance as
   * `modules/domains/repository.ts`'s `findByFrontendToken`.
   */
  consumeIfAvailable(
    token: string,
    now: Date,
  ): Promise<ComponentSessionRow | undefined>
}

export function createComponentSessionsRepository(
  db: Database,
): ComponentSessionsRepository {
  return {
    async create(values) {
      const [row] = await db
        .insert(componentSessions)
        .values({
          projectId: values.projectId,
          mode: values.mode,
          externalId: values.externalId ?? null,
          token: values.token,
          expiresAt: values.expiresAt,
        })
        .returning()

      if (!row) {
        throw new Error(
          'Failed to create component session: insert returned no row',
        )
      }

      return row
    },

    async consumeIfAvailable(token, now) {
      const [row] = await db
        .update(componentSessions)
        .set({ consumedAt: now })
        .where(
          and(
            eq(componentSessions.token, token),
            isNull(componentSessions.consumedAt),
            gt(componentSessions.expiresAt, now),
          ),
        )
        .returning()
      return row
    },
  }
}
