import { and, arrayContains, desc, eq, isNull, sql } from 'drizzle-orm'
import type { Database } from '@infra/db/client'
import { webhookDeliveries, webhookEndpoints } from '@infra/db/schema'
import type { Mode } from '@shared/events'
import type { DeliveriesCursor } from './domain/cursor'

export type WebhookEndpointRow = typeof webhookEndpoints.$inferSelect
export type WebhookDeliveryRow = typeof webhookDeliveries.$inferSelect

export interface WebhookEndpointInsert {
  projectId: string
  mode: Mode
  url: string
  signingSecret: string
  eventTypes: string[]
}

export interface WebhookDeliveryInsert {
  /** Generated by the service (not `defaultRandom()`) so the id is known before insert — see `service.ts`'s `dispatchEvent`, which embeds it in the envelope it's about to persist as `payload`. */
  id: string
  endpointId: string
  eventType: string
  payload: unknown
}

export interface ListDeliveriesOptions {
  limit: number
  cursor?: DeliveriesCursor
}

export interface ListDeliveriesResult {
  rows: WebhookDeliveryRow[]
  /** `true` when more rows exist past the returned page. */
  hasMore: boolean
}

export interface RedeliverLookup {
  endpoint: WebhookEndpointRow
  delivery: WebhookDeliveryRow
}

export interface RetryScheduledUpdate {
  attempt: number
  responseStatus: number | null
  nextRetryAt: Date
}

export interface TerminalDeliveryUpdate {
  responseStatus: number | null
  /** Only meaningful for `markSucceeded`; defaults to "now" there. */
  deliveredAt?: Date
}

/**
 * All db access for the webhooks module — both `webhook_endpoints` and
 * `webhook_deliveries`. This is the only file in `modules/webhooks`
 * allowed to import `@infra/db`.
 */
export interface WebhooksRepository {
  insertEndpoint(values: WebhookEndpointInsert): Promise<WebhookEndpointRow>

  /** All endpoints (any mode, any status) belonging to a project. */
  listEndpointsByProject(projectId: string): Promise<WebhookEndpointRow[]>

  /** Scoped to `projectId`, so an endpoint id belonging to a different project is treated as not found. */
  findEndpoint(
    projectId: string,
    endpointId: string,
  ): Promise<WebhookEndpointRow | undefined>

  /** Returns the deleted row, or `undefined` if `endpointId` doesn't belong to `projectId`. */
  deleteEndpoint(
    projectId: string,
    endpointId: string,
  ): Promise<WebhookEndpointRow | undefined>

  /** Idempotent: disabling an already-disabled endpoint just refreshes `disabledAt`; enabling an already-enabled one is a no-op update. */
  setDisabled(
    projectId: string,
    endpointId: string,
    disabled: boolean,
  ): Promise<WebhookEndpointRow | undefined>

  /**
   * Endpoints that should receive a delivery for `eventType`: matching
   * `projectId` and `mode`, not disabled, and subscribed to `eventType` in
   * their `eventTypes` array. Called from the dispatch subscriber
   * (`service.ts`'s `dispatchEvent`), never from a caller-scoped route —
   * there's no "belongs to the caller" check here because the caller is
   * the event bus, not a session/API key.
   */
  findActiveSubscribed(
    projectId: string,
    mode: Mode,
    eventType: string,
  ): Promise<WebhookEndpointRow[]>

  insertDelivery(values: WebhookDeliveryInsert): Promise<WebhookDeliveryRow>

  /**
   * A delivery joined with its endpoint, scoped through both `projectId`
   * and `endpointId` — the redeliver route needs the original
   * `eventType`/`payload` plus the endpoint's `url`/`signingSecret` to fire
   * a fresh delivery. Returns `undefined` if the delivery, the endpoint, or
   * the (endpoint, project) relationship doesn't match — same
   * anti-enumeration stance as every other project-scoped lookup in this
   * api.
   */
  findDeliveryForRedeliver(
    projectId: string,
    endpointId: string,
    deliveryId: string,
  ): Promise<RedeliverLookup | undefined>

  /** An endpoint's deliveries, newest first, cursor-paginated on `(created_at, id)` descending. */
  listDeliveriesByEndpoint(
    endpointId: string,
    options: ListDeliveriesOptions,
  ): Promise<ListDeliveriesResult>

  markSucceeded(
    deliveryId: string,
    values: TerminalDeliveryUpdate,
  ): Promise<void>
  markFailed(deliveryId: string, values: TerminalDeliveryUpdate): Promise<void>
  markRetryScheduled(
    deliveryId: string,
    values: RetryScheduledUpdate,
  ): Promise<void>
}

export function createWebhooksRepository(db: Database): WebhooksRepository {
  return {
    async insertEndpoint(values) {
      const [row] = await db.insert(webhookEndpoints).values(values).returning()
      if (!row) {
        throw new Error(
          'Failed to create webhook endpoint: insert returned no row',
        )
      }
      return row
    },

    async listEndpointsByProject(projectId) {
      return db
        .select()
        .from(webhookEndpoints)
        .where(eq(webhookEndpoints.projectId, projectId))
    },

    async findEndpoint(projectId, endpointId) {
      const [row] = await db
        .select()
        .from(webhookEndpoints)
        .where(
          and(
            eq(webhookEndpoints.projectId, projectId),
            eq(webhookEndpoints.id, endpointId),
          ),
        )
        .limit(1)
      return row
    },

    async deleteEndpoint(projectId, endpointId) {
      const [row] = await db
        .delete(webhookEndpoints)
        .where(
          and(
            eq(webhookEndpoints.projectId, projectId),
            eq(webhookEndpoints.id, endpointId),
          ),
        )
        .returning()
      return row
    },

    async setDisabled(projectId, endpointId, disabled) {
      const [row] = await db
        .update(webhookEndpoints)
        .set({ disabledAt: disabled ? new Date() : null })
        .where(
          and(
            eq(webhookEndpoints.projectId, projectId),
            eq(webhookEndpoints.id, endpointId),
          ),
        )
        .returning()
      return row
    },

    async findActiveSubscribed(projectId, mode, eventType) {
      return db
        .select()
        .from(webhookEndpoints)
        .where(
          and(
            eq(webhookEndpoints.projectId, projectId),
            eq(webhookEndpoints.mode, mode),
            isNull(webhookEndpoints.disabledAt),
            arrayContains(webhookEndpoints.eventTypes, [eventType]),
          ),
        )
    },

    async insertDelivery(values) {
      const [row] = await db
        .insert(webhookDeliveries)
        .values(values)
        .returning()
      if (!row) {
        throw new Error(
          'Failed to create webhook delivery: insert returned no row',
        )
      }
      return row
    },

    async findDeliveryForRedeliver(projectId, endpointId, deliveryId) {
      const [row] = await db
        .select({ endpoint: webhookEndpoints, delivery: webhookDeliveries })
        .from(webhookDeliveries)
        .innerJoin(
          webhookEndpoints,
          eq(webhookDeliveries.endpointId, webhookEndpoints.id),
        )
        .where(
          and(
            eq(webhookEndpoints.projectId, projectId),
            eq(webhookEndpoints.id, endpointId),
            eq(webhookDeliveries.id, deliveryId),
          ),
        )
        .limit(1)
      return row
    },

    async listDeliveriesByEndpoint(endpointId, { limit, cursor }) {
      // Descending on (created_at, id): the delivery log reads newest
      // first, so the cursor condition anchors on "older than the last row
      // of the previous page" rather than events.ts's ascending ">".
      const cursorCondition = cursor
        ? sql`(${webhookDeliveries.createdAt}, ${webhookDeliveries.id}) < (
            select created_at, id from webhook_deliveries
            where id = ${cursor.id} and endpoint_id = ${endpointId}
          )`
        : undefined

      const rows = await db
        .select()
        .from(webhookDeliveries)
        .where(
          cursorCondition
            ? and(eq(webhookDeliveries.endpointId, endpointId), cursorCondition)
            : eq(webhookDeliveries.endpointId, endpointId),
        )
        .orderBy(desc(webhookDeliveries.createdAt), desc(webhookDeliveries.id))
        .limit(limit + 1)

      const hasMore = rows.length > limit
      return { rows: hasMore ? rows.slice(0, limit) : rows, hasMore }
    },

    async markSucceeded(deliveryId, values) {
      await db
        .update(webhookDeliveries)
        .set({
          status: 'succeeded',
          responseStatus: values.responseStatus,
          deliveredAt: values.deliveredAt ?? new Date(),
          nextRetryAt: null,
        })
        .where(eq(webhookDeliveries.id, deliveryId))
    },

    async markFailed(deliveryId, values) {
      await db
        .update(webhookDeliveries)
        .set({
          status: 'failed',
          responseStatus: values.responseStatus,
          nextRetryAt: null,
        })
        .where(eq(webhookDeliveries.id, deliveryId))
    },

    async markRetryScheduled(deliveryId, values) {
      await db
        .update(webhookDeliveries)
        .set({
          attempt: values.attempt,
          responseStatus: values.responseStatus,
          nextRetryAt: values.nextRetryAt,
        })
        .where(eq(webhookDeliveries.id, deliveryId))
    },
  }
}
