import { createServices } from './app'
import { env } from './env'

const DEMO_CLERK_USER_ID = 'demo-user'
const DEMO_ACCOUNT_EMAIL = 'demo@domainproof.dev'
const DEMO_PROJECT_NAME = 'Demo'

/**
 * Seeds a demo account, a named project, and its test + live API keys on
 * `DATABASE_URL` — for local/staging demos, not production. Goes through
 * `createServices` (see `app.ts`) rather than wiring modules itself, so
 * the seeded data is generated by the exact same services a real signup
 * would use — same event bus, same welcome-email trigger. Refuses to
 * reseed an account that already exists — run `db:reset` first for a
 * clean demo.
 */
async function main() {
  const host = new URL(env.DATABASE_URL).host
  console.log(`db:seed targeting ${host}`)

  const { accountsService, projectsService } = createServices()

  const { created } = await accountsService.ensureAccount(
    DEMO_CLERK_USER_ID,
    DEMO_ACCOUNT_EMAIL,
  )
  if (!created) {
    console.error(
      `A demo account already exists (clerk_user_id=${DEMO_CLERK_USER_ID}) — run db:reset first for a fresh demo seed.`,
    )
    process.exit(1)
  }

  const { project, keys } = await projectsService.createProject(
    DEMO_CLERK_USER_ID,
    DEMO_PROJECT_NAME,
    DEMO_ACCOUNT_EMAIL,
  )

  console.log(`Seeded demo account (clerk_user_id=${DEMO_CLERK_USER_ID})`)
  console.log(`Seeded project "${project.name}" (${project.id})`)
  console.log('')
  console.log(`Test key (shown once): ${keys.test.key}`)
  console.log(`Live key (shown once): ${keys.live.key}`)

  process.exit(0)
}

main().catch((err) => {
  console.error('db:seed failed', err)
  process.exit(1)
})
