import { and, eq } from 'drizzle-orm'
import type { Database } from '@infra/db/client'
import { apiKeys, projects } from '@infra/db/schema'

export type ProjectRow = typeof projects.$inferSelect
export type ProjectApiKeyRow = typeof apiKeys.$inferSelect

/** Ready-to-insert API key material — mirrors `KeysService.ApiKeyMaterial['insert']` structurally, with no import needed (see `createProject`). */
export interface ProjectApiKeyInsert {
  mode: 'test' | 'live'
  keyId: string
  secretHash: string
  last4: string
  name: string | null
}

export interface CreateProjectRowsResult {
  project: ProjectRow
  apiKeys: ProjectApiKeyRow[]
}

/**
 * All db access for the projects module. This is the only file in
 * `modules/projects` allowed to import `@infra/db`. Also touches the
 * `api_keys` table directly (alongside its own `projects` table) inside
 * `createProject`'s transaction — the same shape `modules/accounts`'
 * repository used to insert a project alongside an account, needed here so
 * a project and its bootstrap keys commit atomically.
 */
export interface ProjectsRepository {
  /** All of an account's projects, oldest first (insertion order). */
  listByAccountId(accountId: string): Promise<ProjectRow[]>

  /**
   * A project scoped to the account that's supposed to own it. Returns
   * `undefined` for both "no such project" and "belongs to a different
   * account" — the caller (dashboard keys routes) treats both as a 404,
   * matching the anti-enumeration stance used elsewhere in this api.
   */
  findByIdForAccount(
    projectId: string,
    accountId: string,
  ): Promise<ProjectRow | undefined>

  /** A project's brand slug, e.g. for building its domain verification records. */
  findSlugById(projectId: string): Promise<string | undefined>

  /** A project's display name, e.g. for the Frontend API's hosted verification page. */
  findNameById(projectId: string): Promise<string | undefined>

  /**
   * Updates a project's `name` only — never `slug` (see
   * `ProjectsService.renameProject` for why the slug is frozen at
   * creation). Returns `undefined` if `projectId` doesn't exist.
   */
  updateName(projectId: string, name: string): Promise<ProjectRow | undefined>

  /**
   * Creates a project and its initial API keys (test + live, generated by
   * the caller — see `modules/keys/service.ts`'s `generateKeyMaterial`) in
   * one transaction, so a crash mid-create can never leave a project with
   * no working keys. Unlike account bootstrap, this has no "one winner"
   * conflict handling: multiple projects per account are allowed by
   * design, so two concurrent calls legitimately create two projects
   * rather than racing for a single slot.
   */
  createProject(
    accountId: string,
    name: string,
    slug: string,
    keys: ProjectApiKeyInsert[],
  ): Promise<CreateProjectRowsResult>
}

export function createProjectsRepository(db: Database): ProjectsRepository {
  return {
    async listByAccountId(accountId) {
      return db.select().from(projects).where(eq(projects.accountId, accountId))
    },

    async findByIdForAccount(projectId, accountId) {
      const [project] = await db
        .select()
        .from(projects)
        .where(
          and(eq(projects.id, projectId), eq(projects.accountId, accountId)),
        )
        .limit(1)
      return project
    },

    async findSlugById(projectId) {
      const [project] = await db
        .select({ slug: projects.slug })
        .from(projects)
        .where(eq(projects.id, projectId))
        .limit(1)
      return project?.slug
    },

    async findNameById(projectId) {
      const [project] = await db
        .select({ name: projects.name })
        .from(projects)
        .where(eq(projects.id, projectId))
        .limit(1)
      return project?.name
    },

    async updateName(projectId, name) {
      const [project] = await db
        .update(projects)
        .set({ name })
        .where(eq(projects.id, projectId))
        .returning()
      return project
    },

    async createProject(accountId, name, slug, keys) {
      return db.transaction(async (tx) => {
        const [project] = await tx
          .insert(projects)
          .values({ accountId, name, slug })
          .returning()
        if (!project) {
          throw new Error('Failed to create project: insert returned no row')
        }

        const insertedKeys = await tx
          .insert(apiKeys)
          .values(keys.map((key) => ({ ...key, projectId: project.id })))
          .returning()

        return { project, apiKeys: insertedKeys }
      })
    },
  }
}
